apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  # adopt the docker image build locally inside minikube
  - name: ghcr.io/lsst-sqre/strimzi-registry-operator
    newName: local/strimzi-registry-operator
    newTag: latest

resources:
  - ../../manifests/

patches:
  - path: sro-deployment.yaml
    target:
      kind: Deployment
      name: strimzi-registry-operator
