apiVersion: roundtable.lsst.codes/v1beta1
kind: StrimziSchemaRegistry
metadata:
  name: confluent-schema-registry
  labels:
    strimzi.io/cluster: test-cluster
spec:
  strimziVersion: v1beta2
  listener: tls
  groupId: confluent-schema-registry
  serviceType: NodePort
