name: Minikube integration

"on":
  push:
    branches:
      - "tickets/**"
  workflow_dispatch: {}

jobs:
  minikube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y httpie

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        id: minikube

      - name: Test Minikube cluster
        run: kubectl get nodes

      - name: Set up Kafka with Strimzi
        shell: bash
        working-directory: "minikube"
        run: |
          set -euo pipefail
          ./setupkafka.sh 0.47.0

      - name: Build operator image inside Minikube
        shell: bash
        working-directory: "minikube"
        run: |
          set -euo pipefail
          ./buildimage.sh

      - name: Deploy Strimzi Registry Operator
        shell: bash
        working-directory: "minikube"
        run: |
          set -euo pipefail
          ./deploysro.sh

      - name: Deploy StrimziSchemaRegistry CR
        shell: bash
        working-directory: "minikube"
        run: |
          set -euo pipefail
          ./deployregistry.sh

      - name: Test Registry REST API
        shell: bash
        working-directory: "minikube"
        run: |
          set -euo pipefail
          ./testregistryapi.sh confluent-schema-registry
